#ifndef __AW_MESH_TYPES_H__
#define __AW_MESH_TYPES_H__

#include <stdint.h>
#include <stdbool.h>
#include "AWmeshEvent.h"
#include "AWmeshGatewayApi.h"

//Generic MMDL OPCODES
#define AW_MESH_SIG_MODEL_ID_GENERIC_ONOFF_SERVER    0x1000
#define AW_MESH_SIG_MODEL_ID_GENERIC_ONOFF_CLIENT    0x1001
#define AW_MESH_SIG_MODEL_ID_GENERIC_LEVEL_SERVER    0x1002
#define AW_MESH_SIG_MODEL_ID_GENERIC_LEVEL_CLIENT    0x1003

#define AW_MESH_SIG_MODEL_ID_GENERIC_DEFAULT_TRANSITION_TIME_SERVER    0x1004
#define AW_MESH_SIG_MODEL_ID_GENERIC_DEFAULT_TRANSITION_TIME_CLIENT    0x1005
#define AW_MESH_SIG_MODEL_ID_GENERIC_POWER_ONOFF_SERVER    0x1006
#define AW_MESH_SIG_MODEL_ID_GENERIC_POWER_ONOFF_SETUP_SERVER    0x1007
#define AW_MESH_SIG_MODEL_ID_GENERIC_POWER_ONOFF_CLIENT    0x1008
#define AW_MESH_SIG_MODEL_ID_GENERIC_POWER_LEVEL_SERVER    0x1009
#define AW_MESH_SIG_MODEL_ID_GENERIC_POWER_LEVEL_SETUP_SERVER    0x100a
#define AW_MESH_SIG_MODEL_ID_GENERIC_POWER_LEVEL_CLIENT    0x100b
#define AW_MESH_SIG_MODEL_ID_GENERIC_BATTERY_SERVER    0x100c
#define AW_MESH_SIG_MODEL_ID_GENERIC_BATTERY_CLIENT    0x100d
#define AW_MESH_SIG_MODEL_ID_GENERIC_LOCATION_SERVER    0x100e
#define AW_MESH_SIG_MODEL_ID_GENERIC_LOCATION_SETUP_SERVER    0x100f
#define AW_MESH_SIG_MODEL_ID_GENERIC_LOCATION_CLIENT    0x1010
#define AW_MESH_SIG_MODEL_ID_GENERIC_ADMIN_PROPERTY_SERVER    0x1011
#define AW_MESH_SIG_MODEL_ID_GENERIC_MANUFACTURER_PROPERTY_SERVER    0x1012
#define AW_MESH_SIG_MODEL_ID_GENERIC_USER_PROPERTY_SERVER    0x1013
#define AW_MESH_SIG_MODEL_ID_GENERIC_CLIENT_PROPERTY_SERVER    0x1014
#define AW_MESH_SIG_MODEL_ID_GENERIC_PROPERTY_CLIENT    0x1015
#define AW_MESH_SIG_MODEL_ID_SCENE_CLIENT               0x1205
#define AW_MESH_MODEL_COMPANY_ID_NONE                   0xFFFF
#define AW_MESH_ALI_VENDOR_MODEL_SERVER                 0x01A80000
#define AW_MESH_ALI_VENDOR_MODEL_CLIENT                 0x01A80001
#define AW_MESH_SIG_MODEL_ID_HEALTH_SERVER    0x0002
#define AW_MESH_SIG_MODEL_ID_HEALTH_CLIENT    0x0003

#define AW_MESH_MSG_GENERIC_DTT_GET                        0x820D
#define AW_MESH_MSG_GENERIC_DTT_SET                        0x820E
#define AW_MESH_MSG_GENERIC_DTT_SET_UNACK                  0x820F
#define AW_MESH_MSG_GENERIC_DTT_STAT                       0x8210
#define AW_MESH_MSG_GENERIC_ONOFF_GET                      0x8201
#define AW_MESH_MSG_GENERIC_ONOFF_SET                      0x8202
#define AW_MESH_MSG_GENERIC_ONOFF_SET_UNACK                0x8203
#define AW_MESH_MSG_GENERIC_ONOFF_STATUS                   0x8204
#define AW_MESH_MSG_GENERIC_POWER_LEVEL_GET                0x8215
#define AW_MESH_MSG_GENERIC_POWER_LEVEL_SET                0x8216
#define AW_MESH_MSG_GENERIC_POWER_LEVEL_SET_UNACK          0x8217
#define AW_MESH_MSG_GENERIC_POWER_LEVEL_STAT               0x8218
#define AW_MESH_MSG_GENERIC_POWER_LAST_GET                 0x8219
#define AW_MESH_MSG_GENERIC_POWER_LAST_STAT                0x821A
#define AW_MESH_MSG_GENERIC_POWER_DEFAULT_GET              0x821B
#define AW_MESH_MSG_GENERIC_POWER_DEFAULT_STAT             0x821C
#define AW_MESH_MSG_GENERIC_POWER_RANGE_GET                0x821D
#define AW_MESH_MSG_GENERIC_POWER_RANGE_STAT               0x821E
#define AW_MESH_MSG_GENERIC_POWER_DEFAULT_SET              0x821F
#define AW_MESH_MSG_GENERIC_POWER_DEFAULT_SET_UNACK        0x8220
#define AW_MESH_MSG_GENERIC_POWER_RANGE_SET                0x8221
#define AW_MESH_MSG_GENERIC_POWER_RANGE_SET_UNACK          0x8222

#define AW_MESH_MODEL_GENERIC_POWER_LEVEL_SERVER           0x1009FFFF
#define AW_MESH_MODEL_GENERIC_POWER_LEVEL_SETUP_SERVER     0x100AFFFF
#define AW_MESH_MODEL_GENERIC_POWER_LEVEL_CLIENT           0x100BFFFF

#define AW_MESH_MSG_GENERIC_LOCATION_GLOBAL_GET            0x8225
#define AW_MESH_MSG_GENERIC_LOCATION_GLOBAL_STAT           0x40
#define AW_MESH_MSG_GENERIC_LOCATION_GLOBAL_SET            0x41
#define AW_MESH_MSG_GENERIC_LOCATION_GLOBAL_SET_UNACK      0x42
#define AW_MESH_MSG_GENERIC_LOCATION_LOCAL_GET             0x8226
#define AW_MESH_MSG_GENERIC_LOCATION_LOCAL_STAT            0x8227
#define AW_MESH_MSG_GENERIC_LOCATION_LOCAL_SET             0x8228
#define AW_MESH_MSG_GENERIC_LOCATION_LOCAL_SET_UNACK       0x8229

#define AW_MESH_MODEL_GENERIC_LOCATION_SERVER              0x100EFFFF
#define AW_MESH_MODEL_GENERIC_LOCATION_SETUP_SERVER        0x100FFFFF
#define AW_MESH_MODEL_GENERIC_LOCATION_CLIENT              0x1010FFFF

#define AW_MESH_MSG_GENERIC_LEVEL_GET                      0x8205
#define AW_MESH_MSG_GENERIC_LEVEL_SET                      0x8206
#define AW_MESH_MSG_GENERIC_LEVEL_SET_UNACK                0x8207
#define AW_MESH_MSG_GENERIC_LEVEL_STAT                     0x8208
#define AW_MESH_MSG_GENERIC_DELTA_SET                      0x8209
#define AW_MESH_MSG_GENERIC_DELTA_SET_UNACK                0x820A
#define AW_MESH_MSG_GENERIC_MOVE_SET                       0x820B
#define AW_MESH_MSG_GENERIC_MOVE_SET_UNACK                 0x820C

#define AW_MESH_MODEL_GENERIC_LEVEL_SERVER                 0x1002FFFF
#define AW_MESH_MODEL_GENERIC_LEVEL_CLIENT                 0x1003FFFF

#define AW_MESH_MSG_GENERIC_BATTERY_GET                    0x8223
#define AW_MESH_MSG_GENERIC_BATTERY_STAT                   0x8224

#define AW_MESH_MODEL_GENERIC_BATTERY_SERVER               0x100CFFFF
#define AW_MESH_MODEL_GENERIC_BATTERY_CLIENT               0x100DFFFF

#define AW_MESH_MSG_GENERIC_DEFAULT_TRANSITION_TIME_GET        0x820D
#define AW_MESH_MSG_GENERIC_DEFAULT_TRANSITION_TIME_SET        0x820E
#define AW_MESH_MSG_GENERIC_DEFAULT_TRANSITION_TIME_SET_UNACK  0x820F
#define AW_MESH_MSG_GENERIC_DEFAULT_TRANSITION_TIME_STAT       0x8210

//light MMDL OPCODES
#define AW_MESH_SIG_MODEL_ID_LIGHT_LIGHTNESS_SERVER    0x1300
#define AW_MESH_SIG_MODEL_ID_LIGHT_LIGHTNESS_SETUP_SERVER    0x1301
#define AW_MESH_SIG_MODEL_ID_LIGHT_LIGHTNESS_CLIENT    0x1302
#define AW_MESH_SIG_MODEL_ID_LIGHT_CTL_SERVER    0x1303
#define AW_MESH_SIG_MODEL_ID_LIGHT_CTL_SETUP_SERVER    0x1304
#define AW_MESH_SIG_MODEL_ID_LIGHT_CTL_CLIENT    0x1305
#define AW_MESH_SIG_MODEL_ID_LIGHT_CTL_TEMPERATURE_SERVER    0x1306
#define AW_MESH_SIG_MODEL_ID_LIGHT_HSL_SERVER    0x1307
#define AW_MESH_SIG_MODEL_ID_LIGHT_HSL_SETUP_SERVER    0x1308
#define AW_MESH_SIG_MODEL_ID_LIGHT_HSL_CLIENT    0x1309
#define AW_MESH_SIG_MODEL_ID_LIGHT_HSL_HUE_SERVER    0x130a
#define AW_MESH_SIG_MODEL_ID_LIGHT_HSL_SATURATION_SERVER    0x130b
#define AW_MESH_SIG_MODEL_ID_LIGHT_XYL_SERVER    0x130c
#define AW_MESH_SIG_MODEL_ID_LIGHT_XYL_SETUP_SERVER    0x130d
#define AW_MESH_SIG_MODEL_ID_LIGHT_XYL_CLIENT    0x130e
#define AW_MESH_SIG_MODEL_ID_LIGHT_LC_SERVER    0x130f
#define AW_MESH_SIG_MODEL_ID_LIGHT_LC_LIGHT_ONOFF_SERVER    0x1310
#define AW_MESH_SIG_MODEL_ID_LIGHT_LC_SETUP_SERVER    0x1311
#define AW_MESH_SIG_MODEL_ID_LIGHT_LC_CLIENT    0x1312

//sensor mmdl opcodes
#define AW_MESH_MSG_SENSOR_DESCRIPTOR_GET                    0x8230
#define AW_MESH_MSG_SENSOR_DESCRIPTOR_STATUS                 0x51
#define AW_MESH_MSG_SENSOR_GET                               0x8231
#define AW_MESH_MSG_SENSOR_STATUS                            0x52
#define AW_MESH_MSG_SENSOR_COLUMN_GET                        0x8232
#define AW_MESH_MSG_SENSOR_COLUMN_STATUS                     0x53
#define AW_MESH_MSG_SENSOR_SERIES_GET                        0x8233
#define AW_MESH_MSG_SENSOR_SERIES_STATUS                     0x54
#define AW_MESH_MSG_SENSOR_CADENCE_GET                       0x8234
#define AW_MESH_MSG_SENSOR_CADENCE_SET                       0x55
#define AW_MESH_MSG_SENSOR_CADENCE_SET_UNACK                 0x56
#define AW_MESH_MSG_SENSOR_CADENCE_STATUS                    0x57
#define AW_MESH_MSG_SENSOR_SETTINGS_GET                      0x8235
#define AW_MESH_MSG_SENSOR_SETTINGS_STATUS                   0x58
#define AW_MESH_MSG_SENSOR_SETTING_GET                       0x8236
#define AW_MESH_MSG_SENSOR_SETTING_SET                       0x59
#define AW_MESH_MSG_SENSOR_SETTING_SET_UNACK                 0x5A
#define AW_MESH_MSG_SENSOR_SETTING_STATUS                    0x5B

#define AW_MESH_MODEL_SENSOR_SERVER                          0x1100FFFF
#define AW_MESH_MODEL_SENSOR_SETUP_SERVER                    0x1101FFFF
#define AW_MESH_MODEL_SENSOR_CLIENT                          0x1102FFFF

//timer mmdl opcodes
#define AW_MESH_MSG_TIME_GET                               0x8237
#define AW_MESH_MSG_TIME_SET                               0x5C
#define AW_MESH_MSG_TIME_STATUS                            0x5D
#define AW_MESH_MSG_TIME_ROLE_GET                          0x8238
#define AW_MESH_MSG_TIME_ROLE_SET                          0x8239
#define AW_MESH_MSG_TIME_ROLE_STATUS                       0x823A
#define AW_MESH_MSG_TIME_ZONE_GET                          0x823B
#define AW_MESH_MSG_TIME_ZONE_SET                          0x823C
#define AW_MESH_MSG_TIME_ZONE_STATUS                       0x823D
#define AW_MESH_MSG_TAI_UTC_DELTA_GET                      0x823E
#define AW_MESH_MSG_TAI_UTC_DELTA_SET                      0x823F
#define AW_MESH_MSG_TAI_UTC_DELTA_STATUS                   0x8240

#define AW_MESH_MODEL_TIME_SERVER                          0x1200FFFF
#define AW_MESH_MODEL_TIME_SETUP_SERVER                    0x1201FFFF
#define AW_MESH_MODEL_TIME_CLIENT                          0x1202FFFF

//scheduler modes opcodes
#define AW_MESH_MSG_SCHEDULER_ACTION_GET                   0x8248
#define AW_MESH_MSG_SCHEDULER_ACTION_STATUS                0x5F
#define AW_MESH_MSG_SCHEDULER_GET                          0x8249
#define AW_MESH_MSG_SCHEDULER_STATUS                       0x824A
#define AW_MESH_MSG_SCHEDULER_ACTION_SET                   0x60
#define AW_MESH_MSG_SCHEDULER_ACTION_SET_UNACK             0x61

#define AW_MESH_MODEL_SCHEDULER_SERVER                     0x1206FFFF
#define AW_MESH_MODEL_SCHEDULER_SETUP_SERVER               0x1207FFFF
#define AW_MESH_MODEL_SCHEDULER_CLIENT                     0x1208FFFF


//objects modes opcodes
#define AW_MESH_MSG_OBJ_TRANSFER_GET                             0xB701
#define AW_MESH_MSG_OBJ_TRANSFER_START                           0xB702
#define AW_MESH_MSG_OBJ_TRANSFER_ABORT                     0xB703
#define AW_MESH_MSG_OBJ_TRANSFER_STAT                      0xB704
#define AW_MESH_MSG_OBJ_BLOCK_TRANSFER_START               0xB705
#define AW_MESH_MSG_OBJ_BLOCK_TRANSFER_STAT                0xB706
#define AW_MESH_MSG_OBJ_CHUNCK_TRANSFER                    0x7D
#define AW_MESH_MSG_OBJ_BLOCK_GET                          0x7E
#define AW_MESH_MSG_OBJ_BLOCK_STAT                         0xB709
#define AW_MESH_MSG_OBJ_INFO_GET                           0xB70A
#define AW_MESH_MSG_OBJ_INFO_STAT                          0xB70B
#define AW_MESH_MSG_OBJ_TRANSFER_PHASE_GET                 0xB707
#define AW_MESH_MSG_OBJ_TRANSFER_PHASE_STAT                0xB708
#define AW_MESH_MODEL_OBJ_TRANSFER_SERVER                  0xFF00FFFF
#define AW_MESH_MODEL_OBJ_TRANSFER_CLIENT                  0xFF01FFFF

typedef VOID (*aw_access_opcode_handler_cb_t)(AwMeshEventCb_t event_cb,AW_MESH_ACCESS_MESSAGE_RX_T *p_message);

typedef struct
{
    /** The model opcode. */
    AW_MESH_ACCESS_OPCODE_T opcode;
    /** The opcode handler callback for the given opcode. */
    aw_access_opcode_handler_cb_t handler;
    UINT32 size;
} aw_access_opcode_handler_t;

typedef struct {
    UINT16 location;
    UINT16 *element_index;
} AW_MESH_ELEMENT_DATA_T;

#endif
