#ifndef __AW_MESH_NODE_API_H__
#define __AW_MESH_NODE_API_H__
#include "AWTypes.h"
INT32 aw_mesh_node_cfg_app_key_add(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_APPKEY_ADD_T appkey_add);
INT32 aw_mesh_node_cfg_app_key_update(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_APPKEY_UPDATE_T appkey_update);
INT32 aw_mesh_node_cfg_app_key_delete(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_APPKEY_DEL_T appkey_del);
INT32 aw_mesh_node_cfg_app_key_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_APPKEY_GET_T appkey_get);
INT32 aw_mesh_node_cfg_net_key_add(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_NETKEY_ADD_T netkey_add);
INT32 aw_mesh_node_cfg_net_key_update(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_NETKEY_UPDATE_T netkey_update);
INT32 aw_mesh_node_cfg_net_key_delete(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_NETKEY_DEL_T netkey_del);
INT32 aw_mesh_node_cfg_net_key_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_NETKEY_GET_T netkey_get);
INT32 aw_mesh_node_cfg_model_app_bind(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_MODEL_APP_BIND_T model_app_bind);
INT32 aw_mesh_node_cfg_model_app_unbind(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_MODEL_APP_UNBIND_T model_app_unbind);
INT32 aw_mesh_node_cfg_model_app_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_SIG_MODEL_APP_GET_T sig_model_app_get);
INT32 aw_mesh_node_cfg_vnd_app_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_VENDOR_MODEL_APP_GET_T vendor_model_app_get);
INT32 aw_mesh_node_cfg_compo_data_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_COMPOSITION_DATA_GET_T composition_data_get);
INT32 aw_mesh_node_cfg_beacon_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_BEACON_GET_T beacon_get);
INT32 aw_mesh_node_cfg_beacon_set(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_BEACON_SET_T beacon_set);
INT32 aw_mesh_node_cfg_ttl_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_DEFAULT_TTL_GET_T default_ttl_get);
INT32 aw_mesh_node_cfg_ttl_set(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_DEFAULT_TTL_SET_T default_ttl_set);
INT32 aw_mesh_node_cfg_proxy_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_GATT_PROXY_GET_T gatt_proxy_get);
INT32 aw_mesh_node_cfg_proxy_set(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_GATT_PROXY_SET_T gatt_proxy_set);
INT32 aw_mesh_node_cfg_relay_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_RELAY_GET_T relay_get);
INT32 aw_mesh_node_cfg_relay_set(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_RELAY_SET_T relay_set);
INT32 aw_mesh_node_cfg_transmit_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_NETWORK_TRANSMIT_GET_T net_trans_get);
INT32 aw_mesh_node_cfg_transmit_set(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_NETWORK_TRANSMIT_SET_T net_trans_set);
INT32 aw_mesh_node_cfg_model_pub_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_MODEL_PUB_GET_T model_pub_get);
INT32 aw_mesh_node_cfg_model_pub_set(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_MODEL_PUB_SET_T model_pub_set);
INT32 aw_mesh_node_cfg_model_sub_add(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_MODEL_SUB_ADD_T model_sub_add);
INT32 aw_mesh_node_cfg_model_sub_delete(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_MODEL_SUB_DEL_T model_sub_del);
INT32 aw_mesh_node_cfg_model_sub_delete_all(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_MODEL_SUB_DEL_ALL_T model_sub_del_all);
INT32 aw_mesh_node_cfg_model_sub_overwrite(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_MODEL_SUB_OW_T model_sub_ow);
INT32 aw_mesh_node_cfg_model_sub_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_SIG_MODEL_SUB_GET_T sig_model_sub_get);
INT32 aw_mesh_node_cfg_vnd_sub_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_VENDOR_MODEL_SUB_GET_T vendor_model_sub_get);
INT32 aw_mesh_node_cfg_node_identity_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_NODE_IDENTITY_GET_T node_identity_get);
INT32 aw_mesh_node_cfg_node_identity_set(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_NODE_IDENTITY_SET_T node_identity_set);
INT32 aw_mesh_node_cfg_node_reset(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_NODE_RESET_T node_reset);
INT32 aw_mesh_node_cfg_frnd_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_FRIEND_GET_T friend_get);
INT32 aw_mesh_node_cfg_frnd_set(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_FRIEND_SET_T friend_set);
INT32 aw_mesh_node_cfg_lpn_poll_timeout_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_POLL_TIMEOUT_T poll_timeout);
INT32 aw_mesh_node_cfg_key_refresh_phase_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_KEY_REFRESH_PHASE_GET_T key_ref_pha_get);
INT32 aw_mesh_node_cfg_key_refresh_phase_set(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_KEY_REFRESH_PHASE_SET_T key_ref_pha_set);
INT32 aw_mesh_node_cfg_hb_pub_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_HB_PUB_GET_T hb_pub_get);
INT32 aw_mesh_node_cfg_hb_pub_set(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_HB_PUB_SET_T hb_pub_set);
INT32 aw_mesh_node_cfg_hb_sub_get(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_HB_SUB_GET_T hb_sub_get);
INT32 aw_mesh_node_cfg_hb_sub_set(AW_MESH_CONFIG_META_T meta,UINT16 opcode,AW_MESH_CONFIG_HB_SUB_SET_T hb_sub_set);
#endif
